//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20/01/2025 9:10:58
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class Company {

        public Company()
        {
            this.PowerOfAttorneys_CompanyID = new List<PowerOfAttorney>();
            this.Users = new List<User>();
            OnCreated();
        }

        public virtual int CompanyID { get; set; }

        public virtual string CompanyName { get; set; }

        public virtual string CompanyAddress { get; set; }

        public virtual bool? OwnerSystem { get; set; }

        public virtual DateTime? CreatedDate { get; set; }

        public virtual DateTime? UpdatedDate { get; set; }

        public virtual int? UserManageID { get; set; }

        public virtual bool IsDeleted { get; set; }

        public virtual IList<PowerOfAttorney> PowerOfAttorneys_CompanyID { get; set; }

        public virtual IList<User> Users { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
