//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 08/02/2025 11:07:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class Director {

        public Director()
        {
            OnCreated();
        }

        public virtual int DirectorID { get; set; }

        public virtual int EmployerID { get; set; }

        public virtual string NameTh { get; set; }

        public virtual string NameEng { get; set; }

        public virtual string PositionTh { get; set; }

        public virtual string PositionEng { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual bool? IsActive { get; set; }

        public virtual string UserManager { get; set; }

        public virtual Employer Employer { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
