//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 27/02/2025 15:22:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class Employer {

        public Employer()
        {
            this.Directors = new List<Director>();
            this.EmployerAddresses = new List<EmployerAddress>();
            this.EmployerContacts = new List<EmployerContact>();
            this.EmployerDocuments = new List<EmployerDocument>();
            this.EmployerJobs = new List<EmployerJob>();
            OnCreated();
        }

        public virtual int EmployerID { get; set; }

        public virtual string EmployerCode { get; set; }

        public virtual string NameTh { get; set; }

        public virtual string NameEng { get; set; }

        public virtual int BusinesstypeID { get; set; }

        public virtual string CompanyID { get; set; }

        public virtual DateTime RegistrationDate { get; set; }

        public virtual decimal RegisteredCapital { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual bool? IsActive { get; set; }

        public virtual int UserManageID { get; set; }

        public virtual IList<Director> Directors { get; set; }

        public virtual IList<EmployerAddress> EmployerAddresses { get; set; }

        public virtual IList<EmployerContact> EmployerContacts { get; set; }

        public virtual IList<EmployerDocument> EmployerDocuments { get; set; }

        public virtual IList<EmployerJob> EmployerJobs { get; set; }

        public virtual BusinessType BusinessType { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
