//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02/05/2025 9:20:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class Employer {

        public Employer()
        {
            this.EmployerDocuments = new List<EmployerDocument>();
            this.EmployerAuthorizationConfigs = new List<EmployerAuthorizationConfig>();
            this.EmployerAuthorizedPeople = new List<EmployerAuthorizedPerson>();
            this.Services = new List<Service>();
            OnCreated();
        }

        public virtual int EmployerID { get; set; }

        public virtual string NameTh { get; set; }

        public virtual string NameEng { get; set; }

        public virtual string BusinessTypeName { get; set; }

        public virtual string CardID { get; set; }

        public virtual string RegistrationNumber { get; set; }

        public virtual string RegistrationDate { get; set; }

        public virtual decimal? RegisteredCapital { get; set; }

        public virtual string DirectorNameTh { get; set; }

        public virtual string DirectorNameEng { get; set; }

        public virtual string DirectorPositionTh { get; set; }

        public virtual string DirectorPositionEng { get; set; }

        public virtual string JobTypeName { get; set; }

        public virtual string JobDiscription { get; set; }

        public virtual string OfficerNameOne { get; set; }

        public virtual string OfficerPhoneOne { get; set; }

        public virtual string OfficerNameTwo { get; set; }

        public virtual string OfficerPhoneTwo { get; set; }

        public virtual string HouseRecordNumber { get; set; }

        public virtual string HouseNo { get; set; }

        public virtual string VillageNo { get; set; }

        public virtual string Soi { get; set; }

        public virtual string Road { get; set; }

        public virtual string SubdistrictTh { get; set; }

        public virtual string DistrictTh { get; set; }

        public virtual string ProvinceTh { get; set; }

        public virtual string Postcode { get; set; }

        public virtual string SubdistrictEng { get; set; }

        public virtual string DistrictEng { get; set; }

        public virtual string ProvinceEng { get; set; }

        public virtual string Phone { get; set; }

        public virtual string Fax { get; set; }

        public virtual string Email { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual int UserManageID { get; set; }

        public virtual IList<EmployerDocument> EmployerDocuments { get; set; }

        public virtual User UserManage { get; set; }

        public virtual IList<EmployerAuthorizationConfig> EmployerAuthorizationConfigs { get; set; }

        public virtual IList<EmployerAuthorizedPerson> EmployerAuthorizedPeople { get; set; }

        public virtual IList<Service> Services { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
