//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 08/02/2025 11:07:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class EmployerDocument {

        public EmployerDocument()
        {
            OnCreated();
        }

        public virtual int DocumentID { get; set; }

        public virtual int EmployerID { get; set; }

        public virtual int DocumenttypeID { get; set; }

        public virtual DateTime ExpiryDate { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual bool? IsActive { get; set; }

        public virtual int UserManageID { get; set; }

        public virtual Employer Employer { get; set; }

        public virtual DocumentType DocumentType { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
