//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 06/03/2025 16:41:51
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class EmployerAuthorizationConfig {

        public EmployerAuthorizationConfig()
        {
            OnCreated();
        }

        public virtual int EmployerAuthorizationConfigID { get; set; }

        public virtual int EmployerID { get; set; }

        public virtual int AuthorizedPersonImportID { get; set; }

        public virtual int AuthorizedPersonMouID { get; set; }

        public virtual string Witness1 { get; set; }

        public virtual string Witness2 { get; set; }

        public virtual string AssignorName { get; set; }

        public virtual string AssignorCompany { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual int UserManageID { get; set; }

        public virtual Employer Employer { get; set; }

        public virtual EmployerAuthorizedPerson EmployerAuthorizedPerson_AuthorizedPersonImportID { get; set; }

        public virtual EmployerAuthorizedPerson EmployerAuthorizedPerson_AuthorizedPersonMouID { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
