//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 27/02/2025 15:22:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class EmployerAddress {

        public EmployerAddress()
        {
            OnCreated();
        }

        public virtual int AddressID { get; set; }

        public virtual int EmployerID { get; set; }

        public virtual string HouseNo { get; set; }

        public virtual string Soi { get; set; }

        public virtual string Road { get; set; }

        public virtual string SubdistrictTh { get; set; }

        public virtual string DistrictTh { get; set; }

        public virtual string ProvinceTh { get; set; }

        public virtual string Postcode { get; set; }

        public virtual string SubdistrictEng { get; set; }

        public virtual string DistrictEng { get; set; }

        public virtual string ProvinceEng { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual bool? IsActive { get; set; }

        public virtual int UserManageID { get; set; }

        public virtual Employer Employer { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
