//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 30/04/2025 15:23:21
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class EmployerAuthorizedPerson {

        public EmployerAuthorizedPerson()
        {
            this.EmployerAuthorizationConfigs_AuthorizedPersonImportID = new List<EmployerAuthorizationConfig>();
            this.EmployerAuthorizationConfigs_AuthorizedPersonMouID = new List<EmployerAuthorizationConfig>();
            this.EmployerAuthorizationConfigs_AuthorizedPersonAssignorID = new List<EmployerAuthorizationConfig>();
            this.EmployerAuthorizationConfigs_AuthorizedWitness1ID = new List<EmployerAuthorizationConfig>();
            this.EmployerAuthorizationConfigs_AuthorizedWitness2ID = new List<EmployerAuthorizationConfig>();
            OnCreated();
        }

        public virtual int EmployerAuthorizedPersonID { get; set; }

        public virtual int EmployerID { get; set; }

        public virtual string NameTh { get; set; }

        public virtual string NameEng { get; set; }

        public virtual string LicenseNumber { get; set; }

        public virtual string CompanyName { get; set; }

        public virtual bool? IsAuthorized { get; set; }

        public virtual string CardID { get; set; }

        public virtual string HouseNo { get; set; }

        public virtual string VillageNo { get; set; }

        public virtual string Soi { get; set; }

        public virtual string Road { get; set; }

        public virtual string SubdistrictTh { get; set; }

        public virtual string DistrictTh { get; set; }

        public virtual string ProvinceTh { get; set; }

        public virtual string Phone { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual int UserManageID { get; set; }

        public virtual IList<EmployerAuthorizationConfig> EmployerAuthorizationConfigs_AuthorizedPersonImportID { get; set; }

        public virtual IList<EmployerAuthorizationConfig> EmployerAuthorizationConfigs_AuthorizedPersonMouID { get; set; }

        public virtual Employer Employer { get; set; }

        public virtual User User { get; set; }

        public virtual IList<EmployerAuthorizationConfig> EmployerAuthorizationConfigs_AuthorizedPersonAssignorID { get; set; }

        public virtual IList<EmployerAuthorizationConfig> EmployerAuthorizationConfigs_AuthorizedWitness1ID { get; set; }

        public virtual IList<EmployerAuthorizationConfig> EmployerAuthorizationConfigs_AuthorizedWitness2ID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
