//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 08/02/2025 11:07:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class LogSystemData {

        public LogSystemData()
        {
            OnCreated();
        }

        public virtual int LogID { get; set; }

        public virtual string TableName { get; set; }

        public virtual string Action { get; set; }

        public virtual int RecordID { get; set; }

        public virtual int? UserManageID { get; set; }

        public virtual DateTime? ActionTime { get; set; }

        public virtual string IPAddress { get; set; }

        public virtual string Description { get; set; }

        public virtual string OldValue { get; set; }

        public virtual string NewValue { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
