//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 04/03/2025 10:56:51
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class PowerOfAttorney {

        public PowerOfAttorney()
        {
            this.GrantorApprovalStatus = @"รอการอนุมัติ";
            this.AttorneyApprovalStatus = @"รอการอนุมัติ";
            this.WitnessApprovalStatus1 = @"รอการอนุมัติ";
            this.WitnessApprovalStatus2 = @"รอการอนุมัติ";
            this.Status = @"รอการอนุมัติ";
            OnCreated();
        }

        public virtual int PowerOfAttorneyID { get; set; }

        public virtual string CodeForm { get; set; }

        public virtual int CompanyID { get; set; }

        public virtual DateTime CreationDate { get; set; }

        public virtual int GrantorID { get; set; }

        public virtual int AttorneyID { get; set; }

        public virtual string GrantorApprovalStatus { get; set; }

        public virtual int? GrantorApprovalBy { get; set; }

        public virtual DateTime? GrantorDateApprove { get; set; }

        public virtual string AttorneyApprovalStatus { get; set; }

        public virtual int? AttorneyApprovalBy { get; set; }

        public virtual DateTime? AttorneyDateApprove { get; set; }

        public virtual string WitnessApprovalStatus1 { get; set; }

        public virtual int? WitnessApprovalBy1 { get; set; }

        public virtual DateTime? WitnessDateApprove1 { get; set; }

        public virtual string WitnessApprovalStatus2 { get; set; }

        public virtual int? WitnessApprovalBy2 { get; set; }

        public virtual DateTime? WitnessDateApprove2 { get; set; }

        public virtual string Status { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual int? UserManageID { get; set; }

        public virtual int? UserIDCreated { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual Company Company_CompanyID { get; set; }

        public virtual User User_GrantorID { get; set; }

        public virtual User User_AttorneyID { get; set; }

        public virtual User User_GrantorApprovalBy { get; set; }

        public virtual User User_AttorneyApprovalBy { get; set; }

        public virtual User User_WitnessApprovalBy1 { get; set; }

        public virtual User User_WitnessApprovalBy2 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
