//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 13/01/2025 11:28:34
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class PowerOfAttorney {

        public PowerOfAttorney()
        {
            this.GrantorApprovalStatus = @"รอดำเนินการ";
            this.AttorneyApprovalStatus = @"รอดำเนินการ";
            this.WitnessApprovalStatus1 = @"รอดำเนินการ";
            this.WitnessApprovalStatus2 = @"รอดำเนินการ";
            OnCreated();
        }

        public virtual int DocumentID { get; set; }

        public virtual int CompanyID { get; set; }

        public virtual DateTime CreationDate { get; set; }

        public virtual int GrantorID { get; set; }

        public virtual string GrantorCardID { get; set; }

        public virtual int AttorneyID { get; set; }

        public virtual string AttorneyCardID { get; set; }

        public virtual int AttorneyCompanyID { get; set; }

        public virtual string GrantorApprovalStatus { get; set; }

        public virtual int? GrantorApprovalBy { get; set; }

        public virtual string AttorneyApprovalStatus { get; set; }

        public virtual int? AttorneyApprovalBy { get; set; }

        public virtual string WitnessApprovalStatus1 { get; set; }

        public virtual int? WitnessApprovalBy1 { get; set; }

        public virtual string WitnessApprovalStatus2 { get; set; }

        public virtual int? WitnessApprovalBy2 { get; set; }

        public virtual int? UserManageID { get; set; }

        public virtual bool? IsDeleted { get; set; }

        public virtual Company Company_CompanyID { get; set; }

        public virtual User User_GrantorID { get; set; }

        public virtual User User_AttorneyID { get; set; }

        public virtual Company Company_AttorneyCompanyID { get; set; }

        public virtual User User_GrantorApprovalBy { get; set; }

        public virtual User User_AttorneyApprovalBy { get; set; }

        public virtual User User_WitnessApprovalBy1 { get; set; }

        public virtual User User_WitnessApprovalBy2 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
