//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22/05/2025 9:03:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class Service {

        public Service()
        {
            this.ExpectedPeople = 0;
            this.TotalPrice = 0m;
            this.Deposit = 0m;
            this.RemainingPayment = 0m;
            this.OutstandingAmount = 0m;
            this.ServiceWorkers = new List<ServiceWorker>();
            OnCreated();
        }

        public virtual int ServiceID { get; set; }

        public virtual int EmployerID { get; set; }

        public virtual int ServiceTypeID { get; set; }

        public virtual int ServiceItemID { get; set; }

        public virtual string Note { get; set; }

        public virtual DateTime RecordDate { get; set; }

        public virtual string Recorder { get; set; }

        public virtual string SignatureName { get; set; }

        public virtual bool? IsMou { get; set; }

        public virtual string QuotationNumber { get; set; }

        public virtual int? ExpectedPeople { get; set; }

        public virtual decimal? TotalPrice { get; set; }

        public virtual decimal? Deposit { get; set; }

        public virtual decimal? RemainingPayment { get; set; }

        public virtual decimal? OutstandingAmount { get; set; }

        public virtual string Status { get; set; }

        public virtual bool? IsSentToAccounting { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual int? UserManageID { get; set; }

        public virtual User UserManage { get; set; }

        public virtual Employer Employer { get; set; }

        public virtual ServiceType ServiceType { get; set; }

        public virtual ServiceItem ServiceItem { get; set; }

        public virtual IList<ServiceWorker> ServiceWorkers { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
