//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 28/04/2025 16:31:55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class ServiceWorker {

        public ServiceWorker()
        {
            this.ServiceFee = 0m;
            OnCreated();
        }

        public virtual int ServiceWorkerID { get; set; }

        public virtual int ServiceID { get; set; }

        public virtual string PassportNumber { get; set; }

        public virtual string Nationality { get; set; }

        public virtual string Title { get; set; }

        public virtual string FirstNameEN { get; set; }

        public virtual string LastNameEN { get; set; }

        public virtual decimal? ServiceFee { get; set; }

        public virtual DateTime? Expiry90Days { get; set; }

        public virtual string Note { get; set; }

        public virtual DateTime? DateOfBirth { get; set; }

        public virtual DateTime? PassportIssueDate { get; set; }

        public virtual DateTime? PassportExpiryDate { get; set; }

        public virtual string TypeVisa { get; set; }

        public virtual string WorkPermitNumber { get; set; }

        public virtual DateTime? VisaIssueDate { get; set; }

        public virtual DateTime? VisaExpiryDate { get; set; }

        public virtual string EntryVisaNumber { get; set; }

        public virtual string PlaceOfBirth { get; set; }

        public virtual string PassportIssuedAt { get; set; }

        public virtual string Country { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual int? UserManageID { get; set; }

        public virtual User User { get; set; }

        public virtual Service Service { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
