//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 19/03/2025 14:07:04
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class ServiceItem {

        public ServiceItem()
        {
            this.ServiceWorkers = new List<ServiceWorker>();
            this.Services = new List<Service>();
            OnCreated();
        }

        public virtual int ServiceItemID { get; set; }

        public virtual string ServiceItemName { get; set; }

        public virtual string Descriptions { get; set; }

        public virtual string Note { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual DateTime? CreateAt { get; set; }

        public virtual DateTime? UpdateAt { get; set; }

        public virtual int? UserManageID { get; set; }

        public virtual IList<ServiceWorker> ServiceWorkers { get; set; }

        public virtual User UserManage { get; set; }

        public virtual IList<Service> Services { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
