//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 27/02/2025 15:22:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class User {

        public User()
        {
            this.PowerOfAttorneys_GrantorID = new List<PowerOfAttorney>();
            this.PowerOfAttorneys_AttorneyID = new List<PowerOfAttorney>();
            this.PowerOfAttorneys_GrantorApprovalBy = new List<PowerOfAttorney>();
            this.PowerOfAttorneys_AttorneyApprovalBy = new List<PowerOfAttorney>();
            this.PowerOfAttorneys_WitnessApprovalBy1 = new List<PowerOfAttorney>();
            this.PowerOfAttorneys_WitnessApprovalBy2 = new List<PowerOfAttorney>();
            this.UserPermissions = new List<UserPermission>();
            this.LogSystemDatas = new List<LogSystemData>();
            this.LoginHistories = new List<LoginHistory>();
            this.BusinessTypes = new List<BusinessType>();
            this.DocumentTypes = new List<DocumentType>();
            this.EmployerAddresses = new List<EmployerAddress>();
            this.EmployerContacts = new List<EmployerContact>();
            this.EmployerDocuments = new List<EmployerDocument>();
            this.EmployerJobs = new List<EmployerJob>();
            this.Employers = new List<Employer>();
            OnCreated();
        }

        public virtual int UserID { get; set; }

        public virtual string Username { get; set; }

        public virtual string Passwordhash { get; set; }

        public virtual string FullName { get; set; }

        public virtual int? PositionID { get; set; }

        public virtual int? DepartmentID { get; set; }

        public virtual int? CompanyID { get; set; }

        public virtual string CardID { get; set; }

        public virtual string ProfilePicture { get; set; }

        public virtual string Signature { get; set; }

        public virtual string Email { get; set; }

        public virtual bool ManageSendEmail { get; set; }

        public virtual DateTime? LoginDate { get; set; }

        public virtual DateTime? CreatedDate { get; set; }

        public virtual DateTime? UpdatedDate { get; set; }

        public virtual int? UserManageID { get; set; }

        public virtual bool AdministratorActive { get; set; }

        public virtual bool? IsDeleted { get; set; }

        public virtual Position Position { get; set; }

        public virtual Department Department { get; set; }

        public virtual Company Company { get; set; }

        public virtual IList<PowerOfAttorney> PowerOfAttorneys_GrantorID { get; set; }

        public virtual IList<PowerOfAttorney> PowerOfAttorneys_AttorneyID { get; set; }

        public virtual IList<PowerOfAttorney> PowerOfAttorneys_GrantorApprovalBy { get; set; }

        public virtual IList<PowerOfAttorney> PowerOfAttorneys_AttorneyApprovalBy { get; set; }

        public virtual IList<PowerOfAttorney> PowerOfAttorneys_WitnessApprovalBy1 { get; set; }

        public virtual IList<PowerOfAttorney> PowerOfAttorneys_WitnessApprovalBy2 { get; set; }

        public virtual IList<UserPermission> UserPermissions { get; set; }

        public virtual IList<LogSystemData> LogSystemDatas { get; set; }

        public virtual IList<LoginHistory> LoginHistories { get; set; }

        public virtual IList<BusinessType> BusinessTypes { get; set; }

        public virtual IList<DocumentType> DocumentTypes { get; set; }

        public virtual IList<EmployerAddress> EmployerAddresses { get; set; }

        public virtual IList<EmployerContact> EmployerContacts { get; set; }

        public virtual IList<EmployerDocument> EmployerDocuments { get; set; }

        public virtual IList<EmployerJob> EmployerJobs { get; set; }

        public virtual IList<Employer> Employers { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
