//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20/01/2025 9:10:58
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace WorkPermitManager.Models
{
    public partial class UserPermission {

        public UserPermission()
        {
            OnCreated();
        }

        public virtual int PermissionID { get; set; }

        public virtual int UserID { get; set; }

        public virtual string FunctionName { get; set; }

        public virtual bool? CanCreate { get; set; }

        public virtual bool? CanRead { get; set; }

        public virtual bool? CanUpdate { get; set; }

        public virtual bool? CanDelete { get; set; }

        public virtual DateTime? CreatedDate { get; set; }

        public virtual DateTime? UpdatedDate { get; set; }

        public virtual int? UserManageID { get; set; }

        public virtual bool? IsDeleted { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
