//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 06/06/2025 14:29:07
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using WorkPermitManager.Models;
using Microsoft.Extensions.Configuration;

namespace WorkPermitManager.Data
{

    public partial class Db_WorkPermitManagerModel : DbContext
    {

        public Db_WorkPermitManagerModel() :
            base()
        {
            OnCreated();
        }

        public Db_WorkPermitManagerModel(DbContextOptions<Db_WorkPermitManagerModel> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(GetConnectionString("WorkPermitManagerModelConnectionString"));
                optionsBuilder.UseLazyLoadingProxies();
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        private static string GetConnectionString(string connectionStringName)
        {
            var configurationBuilder = new ConfigurationBuilder().AddJsonFile("appsettings.json", optional: true, reloadOnChange: false);
            var configuration = configurationBuilder.Build();
            return configuration.GetConnectionString(connectionStringName);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<Company> Companies
        {
            get;
            set;
        }

        public virtual DbSet<Department> Departments
        {
            get;
            set;
        }

        public virtual DbSet<Position> Positions
        {
            get;
            set;
        }

        public virtual DbSet<PowerOfAttorney> PowerOfAttorneys
        {
            get;
            set;
        }

        public virtual DbSet<UserPermission> UserPermissions
        {
            get;
            set;
        }

        public virtual DbSet<User> Users
        {
            get;
            set;
        }

        public virtual DbSet<LogSystemData> LogSystemDatas
        {
            get;
            set;
        }

        public virtual DbSet<LoginHistory> LoginHistories
        {
            get;
            set;
        }

        public virtual DbSet<EmployerDocument> EmployerDocuments
        {
            get;
            set;
        }

        public virtual DbSet<Employer> Employers
        {
            get;
            set;
        }

        public virtual DbSet<EmployerAuthorizationConfig> EmployerAuthorizationConfigs
        {
            get;
            set;
        }

        public virtual DbSet<EmployerAuthorizedPerson> EmployerAuthorizedPeople
        {
            get;
            set;
        }

        public virtual DbSet<Service> Services
        {
            get;
            set;
        }

        public virtual DbSet<ServiceItem> ServiceItems
        {
            get;
            set;
        }

        public virtual DbSet<ServiceType> ServiceTypes
        {
            get;
            set;
        }

        public virtual DbSet<ServiceWorker> ServiceWorkers
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            this.CompanyMapping(modelBuilder);
            this.CustomizeCompanyMapping(modelBuilder);

            this.DepartmentMapping(modelBuilder);
            this.CustomizeDepartmentMapping(modelBuilder);

            this.PositionMapping(modelBuilder);
            this.CustomizePositionMapping(modelBuilder);

            this.PowerOfAttorneyMapping(modelBuilder);
            this.CustomizePowerOfAttorneyMapping(modelBuilder);

            this.UserPermissionMapping(modelBuilder);
            this.CustomizeUserPermissionMapping(modelBuilder);

            this.UserMapping(modelBuilder);
            this.CustomizeUserMapping(modelBuilder);

            this.LogSystemDataMapping(modelBuilder);
            this.CustomizeLogSystemDataMapping(modelBuilder);

            this.LoginHistoryMapping(modelBuilder);
            this.CustomizeLoginHistoryMapping(modelBuilder);

            this.EmployerDocumentMapping(modelBuilder);
            this.CustomizeEmployerDocumentMapping(modelBuilder);

            this.EmployerMapping(modelBuilder);
            this.CustomizeEmployerMapping(modelBuilder);

            this.EmployerAuthorizationConfigMapping(modelBuilder);
            this.CustomizeEmployerAuthorizationConfigMapping(modelBuilder);

            this.EmployerAuthorizedPersonMapping(modelBuilder);
            this.CustomizeEmployerAuthorizedPersonMapping(modelBuilder);

            this.ServiceMapping(modelBuilder);
            this.CustomizeServiceMapping(modelBuilder);

            this.ServiceItemMapping(modelBuilder);
            this.CustomizeServiceItemMapping(modelBuilder);

            this.ServiceTypeMapping(modelBuilder);
            this.CustomizeServiceTypeMapping(modelBuilder);

            this.ServiceWorkerMapping(modelBuilder);
            this.CustomizeServiceWorkerMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region Company Mapping

        private void CompanyMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Company>().ToTable(@"Companies", @"dbo");
            modelBuilder.Entity<Company>().Property(x => x.CompanyID).HasColumnName(@"CompanyID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Company>().Property(x => x.CompanyName).HasColumnName(@"CompanyName").HasColumnType(@"nvarchar(255)").IsRequired().ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Company>().Property(x => x.CompanyNameEg).HasColumnName(@"CompanyNameEg").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Company>().Property(x => x.CompanyAddress).HasColumnName(@"CompanyAddress").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Company>().Property(x => x.CompanyAddressEg).HasColumnName(@"CompanyAddressEg").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Company>().Property(x => x.OwnerSystem).HasColumnName(@"OwnerSystem").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<Company>().Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Company>().Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Company>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Company>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<Company>().HasKey(@"CompanyID");
        }

        partial void CustomizeCompanyMapping(ModelBuilder modelBuilder);

        #endregion

        #region Department Mapping

        private void DepartmentMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Department>().ToTable(@"Departments", @"dbo");
            modelBuilder.Entity<Department>().Property(x => x.DepartmentID).HasColumnName(@"DepartmentID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Department>().Property(x => x.DepartmentName).HasColumnName(@"DepartmentName").HasColumnType(@"nvarchar(100)").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<Department>().Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Department>().Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Department>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Department>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<Department>().HasKey(@"DepartmentID");
        }

        partial void CustomizeDepartmentMapping(ModelBuilder modelBuilder);

        #endregion

        #region Position Mapping

        private void PositionMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Position>().ToTable(@"Positions", @"dbo");
            modelBuilder.Entity<Position>().Property(x => x.PositionID).HasColumnName(@"PositionID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Position>().Property(x => x.PositionName).HasColumnName(@"PositionName").HasColumnType(@"nvarchar(100)").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<Position>().Property(x => x.PositionNameEg).HasColumnName(@"PositionNameEg").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<Position>().Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Position>().Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Position>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Position>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<Position>().HasKey(@"PositionID");
        }

        partial void CustomizePositionMapping(ModelBuilder modelBuilder);

        #endregion

        #region PowerOfAttorney Mapping

        private void PowerOfAttorneyMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PowerOfAttorney>().ToTable(@"PowerOfAttorney", @"dbo");
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.PowerOfAttorneyID).HasColumnName(@"PowerOfAttorneyID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.CodeForm).HasColumnName(@"CodeForm").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.CompanyID).HasColumnName(@"CompanyID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.CreationDate).HasColumnName(@"CreationDate").HasColumnType(@"date").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.GrantorID).HasColumnName(@"GrantorID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.AttorneyID).HasColumnName(@"AttorneyID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.GrantorApprovalStatus).HasColumnName(@"GrantorApprovalStatus").HasColumnType(@"nvarchar(20)").ValueGeneratedNever().HasMaxLength(20).HasDefaultValueSql(@"N'รอการอนุมัติ'");
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.GrantorApprovalBy).HasColumnName(@"GrantorApprovalBy").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.GrantorDateApprove).HasColumnName(@"GrantorDateApprove").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.AttorneyApprovalStatus).HasColumnName(@"AttorneyApprovalStatus").HasColumnType(@"nvarchar(20)").ValueGeneratedNever().HasMaxLength(20).HasDefaultValueSql(@"N'รอการอนุมัติ'");
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.AttorneyApprovalBy).HasColumnName(@"AttorneyApprovalBy").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.AttorneyDateApprove).HasColumnName(@"AttorneyDateApprove").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.WitnessApprovalStatus1).HasColumnName(@"WitnessApprovalStatus1").HasColumnType(@"nvarchar(20)").ValueGeneratedNever().HasMaxLength(20).HasDefaultValueSql(@"N'รอการอนุมัติ'");
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.WitnessApprovalBy1).HasColumnName(@"WitnessApprovalBy1").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.WitnessDateApprove1).HasColumnName(@"WitnessDateApprove1").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.WitnessApprovalStatus2).HasColumnName(@"WitnessApprovalStatus2").HasColumnType(@"nvarchar(20)").ValueGeneratedNever().HasMaxLength(20).HasDefaultValueSql(@"N'รอการอนุมัติ'");
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.WitnessApprovalBy2).HasColumnName(@"WitnessApprovalBy2").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.WitnessDateApprove2).HasColumnName(@"WitnessDateApprove2").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.Status).HasColumnName(@"Status").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50).HasDefaultValueSql(@"N'รอการอนุมัติ'");
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.TotalPeople).HasColumnName(@"TotalPeople").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.Remark).HasColumnName(@"Remark").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.UserIDCreated).HasColumnName(@"UserIDCreated").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PowerOfAttorney>().Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"1");
            modelBuilder.Entity<PowerOfAttorney>().HasKey(@"PowerOfAttorneyID");
        }

        partial void CustomizePowerOfAttorneyMapping(ModelBuilder modelBuilder);

        #endregion

        #region UserPermission Mapping

        private void UserPermissionMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserPermission>().ToTable(@"UserPermissions", @"dbo");
            modelBuilder.Entity<UserPermission>().Property(x => x.PermissionID).HasColumnName(@"PermissionID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<UserPermission>().Property(x => x.UserID).HasColumnName(@"UserID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<UserPermission>().Property(x => x.FunctionName).HasColumnName(@"FunctionName").HasColumnType(@"nvarchar(100)").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<UserPermission>().Property(x => x.CanCreate).HasColumnName(@"CanCreate").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<UserPermission>().Property(x => x.CanRead).HasColumnName(@"CanRead").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<UserPermission>().Property(x => x.CanUpdate).HasColumnName(@"CanUpdate").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<UserPermission>().Property(x => x.CanDelete).HasColumnName(@"CanDelete").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<UserPermission>().Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<UserPermission>().Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<UserPermission>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<UserPermission>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<UserPermission>().HasKey(@"PermissionID");
        }

        partial void CustomizeUserPermissionMapping(ModelBuilder modelBuilder);

        #endregion

        #region User Mapping

        private void UserMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>().ToTable(@"Users", @"dbo");
            modelBuilder.Entity<User>().Property(x => x.UserID).HasColumnName(@"UserID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<User>().Property(x => x.Username).HasColumnName(@"Username").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<User>().Property(x => x.Passwordhash).HasColumnName(@"Passwordhash").HasColumnType(@"nvarchar(255)").IsRequired().ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<User>().Property(x => x.FullName).HasColumnName(@"FullName").HasColumnType(@"nvarchar(255)").IsRequired().ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<User>().Property(x => x.FullNameEg).HasColumnName(@"FullNameEg").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<User>().Property(x => x.PositionID).HasColumnName(@"PositionID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<User>().Property(x => x.DepartmentID).HasColumnName(@"DepartmentID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<User>().Property(x => x.CompanyID).HasColumnName(@"CompanyID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<User>().Property(x => x.CardID).HasColumnName(@"CardID").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<User>().Property(x => x.Address).HasColumnName(@"Address").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<User>().Property(x => x.AddressEg).HasColumnName(@"AddressEg").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<User>().Property(x => x.ProfilePicture).HasColumnName(@"ProfilePicture").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<User>().Property(x => x.Signature).HasColumnName(@"Signature").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<User>().Property(x => x.Email).HasColumnName(@"Email").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<User>().Property(x => x.LineWork).HasColumnName(@"LineWork").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<User>().Property(x => x.ManageSendEmail).HasColumnName(@"ManageSendEmail").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<User>().Property(x => x.LoginDate).HasColumnName(@"LoginDate").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<User>().Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<User>().Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<User>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<User>().Property(x => x.AdministratorActive).HasColumnName(@"AdministratorActive").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<User>().Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<User>().HasKey(@"UserID");
            modelBuilder.Entity<User>().HasIndex(@"CardID").IsUnique(true);
        }

        partial void CustomizeUserMapping(ModelBuilder modelBuilder);

        #endregion

        #region LogSystemData Mapping

        private void LogSystemDataMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LogSystemData>().ToTable(@"LogSystemData", @"dbo");
            modelBuilder.Entity<LogSystemData>().Property(x => x.LogID).HasColumnName(@"LogID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<LogSystemData>().Property(x => x.TableName).HasColumnName(@"TableName").HasColumnType(@"nvarchar(100)").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<LogSystemData>().Property(x => x.Action).HasColumnName(@"Action").HasColumnType(@"nvarchar(max)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<LogSystemData>().Property(x => x.RecordID).HasColumnName(@"RecordID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<LogSystemData>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<LogSystemData>().Property(x => x.ActionTime).HasColumnName(@"ActionTime").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<LogSystemData>().Property(x => x.IPAddress).HasColumnName(@"IPAddress").HasColumnType(@"nvarchar(45)").ValueGeneratedNever().HasMaxLength(45);
            modelBuilder.Entity<LogSystemData>().Property(x => x.Description).HasColumnName(@"Description").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<LogSystemData>().Property(x => x.OldValue).HasColumnName(@"OldValue").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<LogSystemData>().Property(x => x.NewValue).HasColumnName(@"NewValue").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<LogSystemData>().HasKey(@"LogID");
        }

        partial void CustomizeLogSystemDataMapping(ModelBuilder modelBuilder);

        #endregion

        #region LoginHistory Mapping

        private void LoginHistoryMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LoginHistory>().ToTable(@"LoginHistory", @"dbo");
            modelBuilder.Entity<LoginHistory>().Property(x => x.LoginID).HasColumnName(@"LoginID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<LoginHistory>().Property(x => x.UserID).HasColumnName(@"UserID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<LoginHistory>().Property(x => x.LoginTime).HasColumnName(@"LoginTime").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<LoginHistory>().Property(x => x.LogoutTime).HasColumnName(@"LogoutTime").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<LoginHistory>().Property(x => x.IPAddress).HasColumnName(@"IPAddress").HasColumnType(@"nvarchar(45)").ValueGeneratedNever().HasMaxLength(45);
            modelBuilder.Entity<LoginHistory>().Property(x => x.DeviceInfo).HasColumnName(@"DeviceInfo").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<LoginHistory>().Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"1");
            modelBuilder.Entity<LoginHistory>().HasKey(@"LoginID");
        }

        partial void CustomizeLoginHistoryMapping(ModelBuilder modelBuilder);

        #endregion

        #region EmployerDocument Mapping

        private void EmployerDocumentMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EmployerDocument>().ToTable(@"EmployerDocuments", @"dbo");
            modelBuilder.Entity<EmployerDocument>().Property(x => x.DocumentID).HasColumnName(@"DocumentID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerDocument>().Property(x => x.DocumentName).HasColumnName(@"DocumentName").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<EmployerDocument>().Property(x => x.EmployerID).HasColumnName(@"EmployerID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerDocument>().Property(x => x.DocumentTypeName).HasColumnName(@"DocumentTypeName").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<EmployerDocument>().Property(x => x.Discription).HasColumnName(@"Discription").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<EmployerDocument>().Property(x => x.ExpiryDate).HasColumnName(@"ExpiryDate").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<EmployerDocument>().Property(x => x.PathFile).HasColumnName(@"PathFile").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<EmployerDocument>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<EmployerDocument>().Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<EmployerDocument>().Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"1");
            modelBuilder.Entity<EmployerDocument>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerDocument>().HasKey(@"DocumentID");
        }

        partial void CustomizeEmployerDocumentMapping(ModelBuilder modelBuilder);

        #endregion

        #region Employer Mapping

        private void EmployerMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Employer>().ToTable(@"Employers", @"dbo");
            modelBuilder.Entity<Employer>().Property(x => x.EmployerID).HasColumnName(@"EmployerID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Employer>().Property(x => x.NameTh).HasColumnName(@"NameTh").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.NameEng).HasColumnName(@"NameEng").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.BusinessTypeName).HasColumnName(@"BusinessTypeName").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.CardID).HasColumnName(@"CardID").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Employer>().Property(x => x.RegistrationNumber).HasColumnName(@"RegistrationNumber").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Employer>().Property(x => x.RegistrationDate).HasColumnName(@"RegistrationDate").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Employer>().Property(x => x.RegisteredCapital).HasColumnName(@"RegisteredCapital").HasColumnType(@"decimal(15,2)").ValueGeneratedNever().HasPrecision(15, 2);
            modelBuilder.Entity<Employer>().Property(x => x.DirectorNameTh).HasColumnName(@"DirectorNameTh").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.DirectorNameEng).HasColumnName(@"DirectorNameEng").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.DirectorPositionTh).HasColumnName(@"DirectorPositionTh").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.DirectorPositionEng).HasColumnName(@"DirectorPositionEng").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.JobTypeName).HasColumnName(@"JobTypeName").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.JobDiscription).HasColumnName(@"JobDiscription").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.OfficerNameOne).HasColumnName(@"OfficerNameOne").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.OfficerPhoneOne).HasColumnName(@"OfficerPhoneOne").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Employer>().Property(x => x.OfficerNameTwo).HasColumnName(@"OfficerNameTwo").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.OfficerPhoneTwo).HasColumnName(@"OfficerPhoneTwo").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Employer>().Property(x => x.HouseRecordNumber).HasColumnName(@"HouseRecordNumber").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Employer>().Property(x => x.HouseNo).HasColumnName(@"HouseNo").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Employer>().Property(x => x.VillageNo).HasColumnName(@"VillageNo").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Employer>().Property(x => x.Soi).HasColumnName(@"Soi").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.Road).HasColumnName(@"Road").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.SubdistrictTh).HasColumnName(@"SubdistrictTh").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.DistrictTh).HasColumnName(@"DistrictTh").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.ProvinceTh).HasColumnName(@"ProvinceTh").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.Postcode).HasColumnName(@"Postcode").HasColumnType(@"nvarchar(10)").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Employer>().Property(x => x.SubdistrictEng).HasColumnName(@"SubdistrictEng").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.DistrictEng).HasColumnName(@"DistrictEng").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.ProvinceEng).HasColumnName(@"ProvinceEng").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.Phone).HasColumnName(@"Phone").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.Fax).HasColumnName(@"Fax").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.Email).HasColumnName(@"Email").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Employer>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Employer>().Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Employer>().Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"1");
            modelBuilder.Entity<Employer>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Employer>().HasKey(@"EmployerID");
        }

        partial void CustomizeEmployerMapping(ModelBuilder modelBuilder);

        #endregion

        #region EmployerAuthorizationConfig Mapping

        private void EmployerAuthorizationConfigMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EmployerAuthorizationConfig>().ToTable(@"EmployerAuthorizationConfig", @"dbo");
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.EmployerAuthorizationConfigID).HasColumnName(@"EmployerAuthorizationConfigID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.EmployerID).HasColumnName(@"EmployerID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.AuthorizedPersonImportID).HasColumnName(@"AuthorizedPersonImportID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.AuthorizedPersonMouID).HasColumnName(@"AuthorizedPersonMouID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.AuthorizedWitness1ID).HasColumnName(@"AuthorizedWitness1ID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.AuthorizedWitness2ID).HasColumnName(@"AuthorizedWitness2ID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.AuthorizedPersonAssignorID).HasColumnName(@"AuthorizedPersonAssignorID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"1");
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<EmployerAuthorizationConfig>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizationConfig>().HasKey(@"EmployerAuthorizationConfigID");
        }

        partial void CustomizeEmployerAuthorizationConfigMapping(ModelBuilder modelBuilder);

        #endregion

        #region EmployerAuthorizedPerson Mapping

        private void EmployerAuthorizedPersonMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EmployerAuthorizedPerson>().ToTable(@"EmployerAuthorizedPerson", @"dbo");
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.EmployerAuthorizedPersonID).HasColumnName(@"EmployerAuthorizedPersonID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.EmployerID).HasColumnName(@"EmployerID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.NameTh).HasColumnName(@"NameTh").HasColumnType(@"nvarchar(255)").IsRequired().ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.NameEng).HasColumnName(@"NameEng").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.LicenseNumber).HasColumnName(@"LicenseNumber").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.CompanyName).HasColumnName(@"CompanyName").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.IsAuthorized).HasColumnName(@"IsAuthorized").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.CardID).HasColumnName(@"CardID").HasColumnType(@"nvarchar(13)").ValueGeneratedNever().HasMaxLength(13);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.HouseNo).HasColumnName(@"HouseNo").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.VillageNo).HasColumnName(@"VillageNo").HasColumnType(@"nvarchar(10)").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.Soi).HasColumnName(@"Soi").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.Road).HasColumnName(@"Road").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.SubdistrictTh).HasColumnName(@"SubdistrictTh").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.DistrictTh).HasColumnName(@"DistrictTh").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.ProvinceTh).HasColumnName(@"ProvinceTh").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.Phone).HasColumnName(@"Phone").HasColumnType(@"nvarchar(20)").ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"1");
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<EmployerAuthorizedPerson>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<EmployerAuthorizedPerson>().HasKey(@"EmployerAuthorizedPersonID");
        }

        partial void CustomizeEmployerAuthorizedPersonMapping(ModelBuilder modelBuilder);

        #endregion

        #region Service Mapping

        private void ServiceMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Service>().ToTable(@"Service", @"dbo");
            modelBuilder.Entity<Service>().Property(x => x.ServiceID).HasColumnName(@"ServiceID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Service>().Property(x => x.EmployerID).HasColumnName(@"EmployerID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Service>().Property(x => x.ServiceTypeID).HasColumnName(@"ServiceTypeID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Service>().Property(x => x.ServiceItemID).HasColumnName(@"ServiceItemID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Service>().Property(x => x.Note).HasColumnName(@"Note").HasColumnType(@"nvarchar(500)").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<Service>().Property(x => x.RecordDate).HasColumnName(@"RecordDate").HasColumnType(@"date").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Service>().Property(x => x.Recorder).HasColumnName(@"Recorder").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<Service>().Property(x => x.SignatureName).HasColumnName(@"SignatureName").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<Service>().Property(x => x.IsMou).HasColumnName(@"IsMou").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<Service>().Property(x => x.QuotationNumber).HasColumnName(@"QuotationNumber").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Service>().Property(x => x.ExpectedPeople).HasColumnName(@"ExpectedPeople").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0).HasDefaultValueSql(@"0");
            modelBuilder.Entity<Service>().Property(x => x.TotalPrice).HasColumnName(@"TotalPrice").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2).HasDefaultValueSql(@"0");
            modelBuilder.Entity<Service>().Property(x => x.Deposit).HasColumnName(@"Deposit").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2).HasDefaultValueSql(@"0");
            modelBuilder.Entity<Service>().Property(x => x.RemainingPayment).HasColumnName(@"RemainingPayment").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2).HasDefaultValueSql(@"0");
            modelBuilder.Entity<Service>().Property(x => x.OutstandingAmount).HasColumnName(@"OutstandingAmount").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2).HasDefaultValueSql(@"0");
            modelBuilder.Entity<Service>().Property(x => x.Status).HasColumnName(@"Status").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Service>().Property(x => x.IsSentToAccounting).HasColumnName(@"IsSentToAccounting").HasColumnType(@"bit").ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<Service>().Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"1");
            modelBuilder.Entity<Service>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Service>().Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Service>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Service>().HasKey(@"ServiceID");
        }

        partial void CustomizeServiceMapping(ModelBuilder modelBuilder);

        #endregion

        #region ServiceItem Mapping

        private void ServiceItemMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ServiceItem>().ToTable(@"ServiceItem", @"dbo");
            modelBuilder.Entity<ServiceItem>().Property(x => x.ServiceItemID).HasColumnName(@"ServiceItemID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<ServiceItem>().Property(x => x.ServiceItemName).HasColumnName(@"ServiceItemName").HasColumnType(@"nvarchar(255)").IsRequired().ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<ServiceItem>().Property(x => x.Descriptions).HasColumnName(@"Descriptions").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<ServiceItem>().Property(x => x.Note).HasColumnName(@"Note").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<ServiceItem>().Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"1");
            modelBuilder.Entity<ServiceItem>().Property(x => x.CreateAt).HasColumnName(@"CreateAt").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<ServiceItem>().Property(x => x.UpdateAt).HasColumnName(@"UpdateAt").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<ServiceItem>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<ServiceItem>().HasKey(@"ServiceItemID");
            modelBuilder.Entity<ServiceItem>().HasIndex(@"ServiceItemName").IsUnique(true);
        }

        partial void CustomizeServiceItemMapping(ModelBuilder modelBuilder);

        #endregion

        #region ServiceType Mapping

        private void ServiceTypeMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ServiceType>().ToTable(@"ServiceType", @"dbo");
            modelBuilder.Entity<ServiceType>().Property(x => x.ServiceTypeID).HasColumnName(@"ServiceTypeID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<ServiceType>().Property(x => x.ServiceTypeName).HasColumnName(@"ServiceTypeName").HasColumnType(@"nvarchar(255)").IsRequired().ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<ServiceType>().Property(x => x.Descriptions).HasColumnName(@"Descriptions").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<ServiceType>().Property(x => x.Note).HasColumnName(@"Note").HasColumnType(@"nvarchar(255)").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<ServiceType>().Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"1");
            modelBuilder.Entity<ServiceType>().Property(x => x.CreateAt).HasColumnName(@"CreateAt").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ServiceType>().Property(x => x.UpdateAt).HasColumnName(@"UpdateAt").HasColumnType(@"datetime").ValueGeneratedNever();
            modelBuilder.Entity<ServiceType>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<ServiceType>().HasKey(@"ServiceTypeID");
            modelBuilder.Entity<ServiceType>().HasIndex(@"ServiceTypeName").IsUnique(true);
        }

        partial void CustomizeServiceTypeMapping(ModelBuilder modelBuilder);

        #endregion

        #region ServiceWorker Mapping

        private void ServiceWorkerMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ServiceWorker>().ToTable(@"ServiceWorker", @"dbo");
            modelBuilder.Entity<ServiceWorker>().Property(x => x.ServiceWorkerID).HasColumnName(@"ServiceWorkerID").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.ServiceID).HasColumnName(@"ServiceID").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.PassportNumber).HasColumnName(@"PassportNumber").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.Nationality).HasColumnName(@"Nationality").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.Title).HasColumnName(@"Title").HasColumnType(@"nvarchar(20)").ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.FirstNameEN).HasColumnName(@"FirstNameEN").HasColumnType(@"nvarchar(100)").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.LastNameEN).HasColumnName(@"LastNameEN").HasColumnType(@"nvarchar(100)").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.ServiceFee).HasColumnName(@"ServiceFee").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2).HasDefaultValueSql(@"0");
            modelBuilder.Entity<ServiceWorker>().Property(x => x.Expiry90Days).HasColumnName(@"Expiry90Days").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.Note).HasColumnName(@"Note").HasColumnType(@"nvarchar(500)").ValueGeneratedNever().HasMaxLength(500);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.BloodType).HasColumnName(@"BloodType").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.DateOfBirth).HasColumnName(@"DateOfBirth").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.PassportExpiryDate).HasColumnName(@"PassportExpiryDate").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.PassportDateOfIssue).HasColumnName(@"PassportDateOfIssue").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.TypeVisa).HasColumnName(@"TypeVisa").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.WorkPermitNumber).HasColumnName(@"WorkPermitNumber").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.VisaExpiryDate).HasColumnName(@"VisaExpiryDate").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.VisaNumber).HasColumnName(@"VisaNumber").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.VisaDateOfIssue).HasColumnName(@"VisaDateOfIssue").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.PlaceOfBirth).HasColumnName(@"PlaceOfBirth").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.VisaIssuedAt).HasColumnName(@"VisaIssuedAt").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.DateOfArrival).HasColumnName(@"DateOfArrival").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.ImmigrationCheckpoint).HasColumnName(@"ImmigrationCheckpoint").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.PermittedUntil).HasColumnName(@"PermittedUntil").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.ResidenceNo).HasColumnName(@"ResidenceNo").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.ResidenceIssuedAt).HasColumnName(@"ResidenceIssuedAt").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.ResidenceProvince).HasColumnName(@"ResidenceProvince").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.ResidenceDateOfIssue).HasColumnName(@"ResidenceDateOfIssue").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.ResidenceExpiryDate).HasColumnName(@"ResidenceExpiryDate").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.AlienNo).HasColumnName(@"AlienNo").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.AlienIssuedAt).HasColumnName(@"AlienIssuedAt").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.AlienProvince).HasColumnName(@"AlienProvince").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.AlienDateOfIssue).HasColumnName(@"AlienDateOfIssue").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.AlienExpiryDate).HasColumnName(@"AlienExpiryDate").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.PassportIssuedAt).HasColumnName(@"PassportIssuedAt").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.WorkPermitDateOfIssue).HasColumnName(@"WorkPermitDateOfIssue").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.Country).HasColumnName(@"Country").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.WorkPermitExpiryDate).HasColumnName(@"WorkPermitExpiryDate").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<ServiceWorker>().Property(x => x.WorkPermitIssuedAtProvince).HasColumnName(@"WorkPermitIssuedAtProvince").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.WorkPermitActionType).HasColumnName(@"WorkPermitActionType").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ServiceWorker>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<ServiceWorker>().Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<ServiceWorker>().Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"1");
            modelBuilder.Entity<ServiceWorker>().Property(x => x.UserManageID).HasColumnName(@"UserManageID").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<ServiceWorker>().HasKey(@"ServiceWorkerID");
        }

        partial void CustomizeServiceWorkerMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Company>().HasMany(x => x.PowerOfAttorneys_CompanyID).WithOne(op => op.Company_CompanyID).IsRequired(true).HasForeignKey(@"CompanyID");
            modelBuilder.Entity<Company>().HasMany(x => x.Users).WithOne(op => op.Company).IsRequired(false).HasForeignKey(@"CompanyID");

            modelBuilder.Entity<Department>().HasMany(x => x.Users).WithOne(op => op.Department).IsRequired(false).HasForeignKey(@"DepartmentID");

            modelBuilder.Entity<Position>().HasMany(x => x.Users).WithOne(op => op.Position).IsRequired(false).HasForeignKey(@"PositionID");

            modelBuilder.Entity<PowerOfAttorney>().HasOne(x => x.Company_CompanyID).WithMany(op => op.PowerOfAttorneys_CompanyID).IsRequired(true).HasForeignKey(@"CompanyID");
            modelBuilder.Entity<PowerOfAttorney>().HasOne(x => x.User_GrantorID).WithMany(op => op.PowerOfAttorneys_GrantorID).IsRequired(true).HasForeignKey(@"GrantorID");
            modelBuilder.Entity<PowerOfAttorney>().HasOne(x => x.User_AttorneyID).WithMany(op => op.PowerOfAttorneys_AttorneyID).IsRequired(false).HasForeignKey(@"AttorneyID");
            modelBuilder.Entity<PowerOfAttorney>().HasOne(x => x.User_GrantorApprovalBy).WithMany(op => op.PowerOfAttorneys_GrantorApprovalBy).IsRequired(false).HasForeignKey(@"GrantorApprovalBy");
            modelBuilder.Entity<PowerOfAttorney>().HasOne(x => x.User_AttorneyApprovalBy).WithMany(op => op.PowerOfAttorneys_AttorneyApprovalBy).IsRequired(false).HasForeignKey(@"AttorneyApprovalBy");
            modelBuilder.Entity<PowerOfAttorney>().HasOne(x => x.User_WitnessApprovalBy1).WithMany(op => op.PowerOfAttorneys_WitnessApprovalBy1).IsRequired(false).HasForeignKey(@"WitnessApprovalBy1");
            modelBuilder.Entity<PowerOfAttorney>().HasOne(x => x.User_WitnessApprovalBy2).WithMany(op => op.PowerOfAttorneys_WitnessApprovalBy2).IsRequired(false).HasForeignKey(@"WitnessApprovalBy2");

            modelBuilder.Entity<UserPermission>().HasOne(x => x.User).WithMany(op => op.UserPermissions).IsRequired(true).HasForeignKey(@"UserID");

            modelBuilder.Entity<User>().HasOne(x => x.Position).WithMany(op => op.Users).IsRequired(false).HasForeignKey(@"PositionID");
            modelBuilder.Entity<User>().HasOne(x => x.Department).WithMany(op => op.Users).IsRequired(false).HasForeignKey(@"DepartmentID");
            modelBuilder.Entity<User>().HasOne(x => x.Company).WithMany(op => op.Users).IsRequired(false).HasForeignKey(@"CompanyID");
            modelBuilder.Entity<User>().HasMany(x => x.PowerOfAttorneys_GrantorID).WithOne(op => op.User_GrantorID).IsRequired(true).HasForeignKey(@"GrantorID");
            modelBuilder.Entity<User>().HasMany(x => x.PowerOfAttorneys_AttorneyID).WithOne(op => op.User_AttorneyID).IsRequired(false).HasForeignKey(@"AttorneyID");
            modelBuilder.Entity<User>().HasMany(x => x.PowerOfAttorneys_GrantorApprovalBy).WithOne(op => op.User_GrantorApprovalBy).IsRequired(false).HasForeignKey(@"GrantorApprovalBy");
            modelBuilder.Entity<User>().HasMany(x => x.PowerOfAttorneys_AttorneyApprovalBy).WithOne(op => op.User_AttorneyApprovalBy).IsRequired(false).HasForeignKey(@"AttorneyApprovalBy");
            modelBuilder.Entity<User>().HasMany(x => x.PowerOfAttorneys_WitnessApprovalBy1).WithOne(op => op.User_WitnessApprovalBy1).IsRequired(false).HasForeignKey(@"WitnessApprovalBy1");
            modelBuilder.Entity<User>().HasMany(x => x.PowerOfAttorneys_WitnessApprovalBy2).WithOne(op => op.User_WitnessApprovalBy2).IsRequired(false).HasForeignKey(@"WitnessApprovalBy2");
            modelBuilder.Entity<User>().HasMany(x => x.UserPermissions).WithOne(op => op.User).IsRequired(true).HasForeignKey(@"UserID");
            modelBuilder.Entity<User>().HasMany(x => x.LogSystemDatas).WithOne(op => op.User).IsRequired(false).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<User>().HasMany(x => x.LoginHistories).WithOne(op => op.User).IsRequired(true).HasForeignKey(@"UserID");
            modelBuilder.Entity<User>().HasMany(x => x.EmployerDocuments).WithOne(op => op.User).IsRequired(true).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<User>().HasMany(x => x.Employers).WithOne(op => op.UserManage).IsRequired(true).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<User>().HasMany(x => x.EmployerAuthorizationConfigs).WithOne(op => op.User).IsRequired(true).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<User>().HasMany(x => x.EmployerAuthorizedPeople).WithOne(op => op.User).IsRequired(true).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<User>().HasMany(x => x.Services).WithOne(op => op.UserManage).IsRequired(false).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<User>().HasMany(x => x.ServiceItems).WithOne(op => op.UserManage).IsRequired(false).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<User>().HasMany(x => x.ServiceTypes).WithOne(op => op.UserManage).IsRequired(true).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<User>().HasMany(x => x.ServiceWorkers).WithOne(op => op.User).IsRequired(false).HasForeignKey(@"UserManageID");

            modelBuilder.Entity<LogSystemData>().HasOne(x => x.User).WithMany(op => op.LogSystemDatas).IsRequired(false).HasForeignKey(@"UserManageID");

            modelBuilder.Entity<LoginHistory>().HasOne(x => x.User).WithMany(op => op.LoginHistories).IsRequired(true).HasForeignKey(@"UserID");

            modelBuilder.Entity<EmployerDocument>().HasOne(x => x.Employer).WithMany(op => op.EmployerDocuments).IsRequired(true).HasForeignKey(@"EmployerID");
            modelBuilder.Entity<EmployerDocument>().HasOne(x => x.User).WithMany(op => op.EmployerDocuments).IsRequired(true).HasForeignKey(@"UserManageID");

            modelBuilder.Entity<Employer>().HasMany(x => x.EmployerDocuments).WithOne(op => op.Employer).IsRequired(true).HasForeignKey(@"EmployerID");
            modelBuilder.Entity<Employer>().HasOne(x => x.UserManage).WithMany(op => op.Employers).IsRequired(true).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<Employer>().HasMany(x => x.EmployerAuthorizationConfigs).WithOne(op => op.Employer).IsRequired(true).HasForeignKey(@"EmployerID");
            modelBuilder.Entity<Employer>().HasMany(x => x.EmployerAuthorizedPeople).WithOne(op => op.Employer).IsRequired(true).HasForeignKey(@"EmployerID");
            modelBuilder.Entity<Employer>().HasMany(x => x.Services).WithOne(op => op.Employer).IsRequired(true).HasForeignKey(@"EmployerID");

            modelBuilder.Entity<EmployerAuthorizationConfig>().HasOne(x => x.Employer).WithMany(op => op.EmployerAuthorizationConfigs).IsRequired(true).HasForeignKey(@"EmployerID");
            modelBuilder.Entity<EmployerAuthorizationConfig>().HasOne(x => x.EmployerAuthorizedPerson_AuthorizedPersonImportID).WithMany(op => op.EmployerAuthorizationConfigs_AuthorizedPersonImportID).IsRequired(true).HasForeignKey(@"AuthorizedPersonImportID");
            modelBuilder.Entity<EmployerAuthorizationConfig>().HasOne(x => x.EmployerAuthorizedPerson_AuthorizedPersonMouID).WithMany(op => op.EmployerAuthorizationConfigs_AuthorizedPersonMouID).IsRequired(true).HasForeignKey(@"AuthorizedPersonMouID");
            modelBuilder.Entity<EmployerAuthorizationConfig>().HasOne(x => x.User).WithMany(op => op.EmployerAuthorizationConfigs).IsRequired(true).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<EmployerAuthorizationConfig>().HasOne(x => x.EmployerAuthorizedPerson_AuthorizedPersonAssignorID).WithMany(op => op.EmployerAuthorizationConfigs_AuthorizedPersonAssignorID).IsRequired(true).HasForeignKey(@"AuthorizedPersonAssignorID");
            modelBuilder.Entity<EmployerAuthorizationConfig>().HasOne(x => x.EmployerAuthorizedPerson_AuthorizedWitness1ID).WithMany(op => op.EmployerAuthorizationConfigs_AuthorizedWitness1ID).IsRequired(false).HasForeignKey(@"AuthorizedWitness1ID");
            modelBuilder.Entity<EmployerAuthorizationConfig>().HasOne(x => x.EmployerAuthorizedPerson_AuthorizedWitness2ID).WithMany(op => op.EmployerAuthorizationConfigs_AuthorizedWitness2ID).IsRequired(false).HasForeignKey(@"AuthorizedWitness2ID");

            modelBuilder.Entity<EmployerAuthorizedPerson>().HasMany(x => x.EmployerAuthorizationConfigs_AuthorizedPersonImportID).WithOne(op => op.EmployerAuthorizedPerson_AuthorizedPersonImportID).IsRequired(true).HasForeignKey(@"AuthorizedPersonImportID");
            modelBuilder.Entity<EmployerAuthorizedPerson>().HasMany(x => x.EmployerAuthorizationConfigs_AuthorizedPersonMouID).WithOne(op => op.EmployerAuthorizedPerson_AuthorizedPersonMouID).IsRequired(true).HasForeignKey(@"AuthorizedPersonMouID");
            modelBuilder.Entity<EmployerAuthorizedPerson>().HasOne(x => x.Employer).WithMany(op => op.EmployerAuthorizedPeople).IsRequired(true).HasForeignKey(@"EmployerID");
            modelBuilder.Entity<EmployerAuthorizedPerson>().HasOne(x => x.User).WithMany(op => op.EmployerAuthorizedPeople).IsRequired(true).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<EmployerAuthorizedPerson>().HasMany(x => x.EmployerAuthorizationConfigs_AuthorizedPersonAssignorID).WithOne(op => op.EmployerAuthorizedPerson_AuthorizedPersonAssignorID).IsRequired(true).HasForeignKey(@"AuthorizedPersonAssignorID");
            modelBuilder.Entity<EmployerAuthorizedPerson>().HasMany(x => x.EmployerAuthorizationConfigs_AuthorizedWitness1ID).WithOne(op => op.EmployerAuthorizedPerson_AuthorizedWitness1ID).IsRequired(false).HasForeignKey(@"AuthorizedWitness1ID");
            modelBuilder.Entity<EmployerAuthorizedPerson>().HasMany(x => x.EmployerAuthorizationConfigs_AuthorizedWitness2ID).WithOne(op => op.EmployerAuthorizedPerson_AuthorizedWitness2ID).IsRequired(false).HasForeignKey(@"AuthorizedWitness2ID");

            modelBuilder.Entity<Service>().HasOne(x => x.UserManage).WithMany(op => op.Services).IsRequired(false).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<Service>().HasOne(x => x.Employer).WithMany(op => op.Services).IsRequired(true).HasForeignKey(@"EmployerID");
            modelBuilder.Entity<Service>().HasOne(x => x.ServiceType).WithMany(op => op.Services).IsRequired(true).HasForeignKey(@"ServiceTypeID");
            modelBuilder.Entity<Service>().HasOne(x => x.ServiceItem).WithMany(op => op.Services).IsRequired(true).HasForeignKey(@"ServiceItemID");
            modelBuilder.Entity<Service>().HasMany(x => x.ServiceWorkers).WithOne(op => op.Service).IsRequired(true).HasForeignKey(@"ServiceID");

            modelBuilder.Entity<ServiceItem>().HasOne(x => x.UserManage).WithMany(op => op.ServiceItems).IsRequired(false).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<ServiceItem>().HasMany(x => x.Services).WithOne(op => op.ServiceItem).IsRequired(true).HasForeignKey(@"ServiceItemID");

            modelBuilder.Entity<ServiceType>().HasOne(x => x.UserManage).WithMany(op => op.ServiceTypes).IsRequired(true).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<ServiceType>().HasMany(x => x.Services).WithOne(op => op.ServiceType).IsRequired(true).HasForeignKey(@"ServiceTypeID");

            modelBuilder.Entity<ServiceWorker>().HasOne(x => x.User).WithMany(op => op.ServiceWorkers).IsRequired(false).HasForeignKey(@"UserManageID");
            modelBuilder.Entity<ServiceWorker>().HasOne(x => x.Service).WithMany(op => op.ServiceWorkers).IsRequired(true).HasForeignKey(@"ServiceID");
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
